os:
  - linux
  - osx

language: cpp

compiler:
  - clang

dist: trusty

addons:
  apt:
   packages:
    - qt5-default
    - qt5-qmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi

script:
  - qmake robocut.pro
  - make
  