os:
  - linux
  - osx

language: cpp

compiler:
  - clang

dist: trusty

addons:
  apt:
   packages:
    - qt5-default
    - qt5-qmake
    - libqt5svg5-dev
    - libusb-1.0-0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 libusb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt ; fi

script:
  - qmake Robocut.pro
  - make
  