os:
  - linux
  - osx

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - gcc-7
      - g++-7
      - cmake
      - qt510-meta-minimal
      - qt510svg
      - qt510imageformats
      - qt510tools
      - libusb-1.0-0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 libusb cmake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt ; fi

script:
  - if [[ "TRAVIS_OS_NAME" == "linux "]]; then g++ --version ; fi
  - if [[ "TRAVIS_OS_NAME" == "linux "]]; then /usr/local/bin/g++ --version ; fi
  - cmake --version
  - qmake Robocut.pro
  - make
  